# Basics of CuPy

**Negin Sobhani**, **Deepak Cherian**, and **Max Jones**

negins@ucar.edu, dcherian@ucar.edu, max@carbonplan.org

------------

## Overview
### In this tutorial, you learn:

* Basics of Cupy and GPU comuting
* Compare speeds to NumPy

## Introduction to CuPy
CuPy is an open-source GPU-accelerated array library for Python that is compatible with NumPy. 

<img src="https://miro.medium.com/v2/resize:fit:720/format:webp/0*Qg5AIeVmg2nnP2XV.png" width="500">

CuPy uses NVIDIA CUDA to run operations on the GPU, which can provide significant performance improvements for numerical computations compared to running on the CPU. CuPy provides a NumPy-like interface for array manipulation and supports a wide range of mathematical operations, making it a powerful tool for scientific computing.

<div class="alert alert-block alert-success">
<b> In simple terms, CuPy can be described as the GPU equivalent of NumPy.</b>
</div>

CuPy is a library that parallels NumPy's capabilities, but with a few key distinctions that are important for GPU computing. It provides:

* An object similar to NumPy's multidimensional array, except that it resides in the memory of the GPU, allowing for faster computations involving large data sets.

* A system for applying "universal functions" (ufuncs) that adhere to broadcasting rules. This system leverages the parallel computing power of GPUs for better performance.

* CuPy provides an extensive collection of CUDA-ready array functions. CUDA is NVIDIA's parallel computing platform and API model, which allows software developers to use a CUDA-enabled GPU for general purpose processing. CuPy's extensive set of pre-implemented mathematical functions can be used on arrays right off the bat, taking full advantage of GPU acceleration.

For more information about CuPy, please visit:

[CuPy Homepage](https://docs.cupy.dev/en/stable/index.html#)

[CuPy Github](https://github.com/cupy/cupy)

Throughout this tutorial, we will delve into these unique aspects of CuPy and demonstrate how they compare to their NumPy counterparts. Let's get started!

## Getting Started with CuPy

After the installation of CuPy, we can import it similar to Numpy:

In [1]:
## Import NumPy and CuPy
import cupy as cp
import numpy as np

### Arrays in CuPy vs. NumPy

CuPy arrays can be declared using the `cupy.ndarray` class, much like NumPy arrays using `numpy.ndarrays`. However, it is important to note that while NumPy arrays are generated on the CPU (referred to as the "host"), CuPy arrays are generated on the GPU (known as the "device").

CuPy arrays look just like NumPy arrays:

In [2]:
# create a 1D array with 5 elements on CPU
arr_cpu = np.array([1, 2, 3, 4, 5])
print("On the CPU: ", arr_cpu)
print (type(arr_cpu))

On the CPU:  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# create a 1D array with 5 elements on GPU
arr_gpu = cp.array([1, 2, 3, 4, 5])
print("On the GPU: ", arr_gpu)
print (type(arr_gpu))

On the GPU:  [1 2 3 4 5]
<class 'cupy.ndarray'>


 You can also create multi-dimensional arrays:

In [4]:
# create a 2D array of zeros with 3 rows and 4 columns
arr_cpu = np.zeros((3, 4))
print("On the CPU: ", arr_cpu)
print (type(arr_cpu))

On the CPU:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [5]:
arr_gpu = cp.zeros((3, 4))
print("On the GPU: ", arr_gpu)
print (type(arr_gpu))

On the GPU:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'cupy.ndarray'>


As we can see in the above examples, CuPy arrays look just like NumPy arrays, except that Cupy arrays are stored on GPUs vs. Numpy arrays are stored on CPUs. 

### Basic Operations 
CuPy provides equivalents for many common NumPy functions, although not all. Most of CuPy's functions have the same function call as their NumPy counterparts. See the reference for the supported subset of NumPy API.
| | |
| :--- | :--- |
| **NumPy** | **CuPy** |
| numpy.identity        | cupy.identity       |
| numpy.matmul        | cupy.matmul       |
| numpy.nan_to_num        | cupy.nan_to_num       |
| numpy.zeros        | cupy.zeros       |
| numpy.ones        | cupy.ones       |
| numpy.shape        | cupy.shape       |
| numpy.reshape        | cupy.reshape       |
| numpy.tensordot        | cupy.tensordot       |
| numpy.transpose        | cupy.transpose       |
| numpy.fft.fft        | cupy.fft.fft       |

Cupy also provides equivalant functions for some SciPy functions, but its implementation is not as extensive as NumPy's.

A full list of CuPy's Numpy and Scipy equivalent functions are provided on the link below:

[Complete Comparison of NumPy and SciPy to CuPy functions](https://docs.cupy.dev/en/stable/reference/comparison.html)

[CuPy API Reference](https://docs.cupy.dev/en/stable/reference/index.html)

In [6]:
# NumPy: Create an array
numpy_a = np.array([1, 2, 3, 4, 5])

# CuPy: Create an array
cupy_a = cp.array([1, 2, 3, 4, 5])

Basic arithmetic operations is exactly identical between numpy and cupy. 

In [7]:
# Basic arithmetic operations
numpy_b = numpy_a + 2
cupy_b = cupy_a + 2

numpy_c = numpy_a * 2
cupy_c = cupy_a * 2

numpy_d = numpy_a.dot(numpy_a)
cupy_d = cupy_a.dot(cupy_a)

# Reshaping arrays
numpy_e = numpy_a.reshape(5, 1)
cupy_e = cupy_a.reshape(5, 1)

# Transposing arrays
numpy_f = numpy_e.T
cupy_f = cupy_e.T

# Complex example: element-wise exponential and sum
numpy_g = np.exp(numpy_a) / np.sum(np.exp(numpy_a))
cupy_g = cp.exp(cupy_a) / cp.sum(cp.exp(cupy_a))

### Data Transfer

#### Data Transfer to a Device
`cupy.asarray()` can be used to move a numpy array to a device (GPU).

In [8]:
# Move data to GPU
arr_gpu = cp.asarray(arr_cpu)

#### Move array from GPU to the host

Moving a device array to the host can be done by `cupy.asnumpy()` as follows:

In [9]:
# Move data back to host
arr_cpu = cp.asnumpy(arr_gpu)

We can also use `cupy.ndarray.get()`:

In [10]:
arr_cpu = arr_gpu.get()

### Device Information 
CuPy introduces the concept of a current device, which represents the default GPU device for array allocation, manipulation, calculations, and other operations. 

`cupy.ndarray.device` attribute can be used to determine the device allocated to a CUPY array: 

In [11]:
cupy_g.device

<CUDA Device 0>

To obtain the total number of accessible devices, you can utilize the getDeviceCount function.

In [12]:
cp.cuda.runtime.getDeviceCount()

1

The default behavior runs code on Device 0, but we can transfer arrays other devices with CuPy using `cp.cuda.Device()`. This capability becomes significantly important when your code is designed to harness the power of multiple GPUs. For example the following create an array on the GPU 2. 

``` python 
with cp.cuda.Device(2):
    x_on_gpu2 = cp.array([1, 2, 3, 4, 5])
```

## CuPy vs NumPy: Speed Comparison

Now, let's explore the tangible benefits of using CuPy when dealing with large datasets. In particular, let's examine the significant performance improvements that CuPy can provide in comparison to NumPy.

In [13]:
import time

# create two 1000x1000 matrices
n = 3000

a_np = np.random.rand(n, n)
b_np = np.random.rand(n, n)

a_cp = cp.asarray(a_np)
b_cp = cp.asarray(b_np)

# perform matrix multiplication with NumPy and time it
start_time = time.time()
c_np = np.dot(a_np, b_np)
end_time = time.time()

numpy_time = end_time - start_time
print("NumPy time:", numpy_time, "seconds")

# perform matrix multiplication with CuPy and time it
start_time = time.time()
c_cp = cp.dot(a_cp, b_cp)
cp.cuda.Stream.null.synchronize()  # wait for GPU computation to finish
end_time = time.time()

cupy_time = end_time - start_time

print("CuPy time:", cupy_time, "seconds")
print("CuPy provides a", round(numpy_time / cupy_time, 2), "x speedup over NumPy.")

NumPy time: 0.6037507057189941 seconds
CuPy time: 0.43988704681396484 seconds
CuPy provides a 1.37 x speedup over NumPy.


Now, let's make the same comparison with other array sizes:

In [14]:
for n in [10, 100, 1000, 5000, 10000]:
    print("n =", n)

    # create two nxn matrices
    a_np = np.random.rand(n, n)
    b_np = np.random.rand(n, n)
    a_cp = cp.asarray(a_np)
    b_cp = cp.asarray(b_np)

    # perform matrix multiplication with NumPy and time it
    start_time = time.time()
    c_np = np.dot(a_np, b_np)
    end_time = time.time()
    numpy_time = end_time - start_time

    # perform matrix multiplication with CuPy and time it
    start_time = time.time()
    c_cp = cp.dot(a_cp, b_cp)
    cp.cuda.Stream.null.synchronize()  # wait for GPU computation to finish
    end_time = time.time()
    cupy_time = end_time - start_time

    # print the speedup
    print("CuPy provides a", round(numpy_time / cupy_time,2), "x speedup over NumPy.\n")

n = 10
CuPy provides a 1.85 x speedup over NumPy.

n = 100
CuPy provides a 0.98 x speedup over NumPy.

n = 1000
CuPy provides a 43.48 x speedup over NumPy.

n = 5000
CuPy provides a 71.07 x speedup over NumPy.

n = 10000
CuPy provides a 67.87 x speedup over NumPy.



As we can see above, GPUs can be much slower than CPUs. There are several reasons for this: 
    
* The size of our arrays: The GPU's performance relies on parallelism, processing thousands of values simultaneously. To fully leverage the GPU's capabilities, we require a significantly larger array.

* The simplicity of our calculation: Transferring a calculation to the GPU involves considerable overhead compared to executing a function on the CPU. If our calculation lacks a sufficient number of mathematical operations (known as "arithmetic intensity"), the GPU will spend most of its time waiting for data movement.

* Data copying to and from the GPU impacts performance: While including copy time can be realistic for a single function, there are instances where we need to execute multiple GPU operations sequentially. In such cases, it is advantageous to transfer data to the GPU and keep it there until all processing is complete.

In [15]:
Congratulations! You have now uncovered the capabilities of CuPy. It's time to unleash its power and accelerate your own code by seamlessly replacing NumPy with CuPy wherever applicable. 

## Summary

In this notebook, we have learned about:

* Cupy Basics
* Performance Cupy vs. Numpy on different array sizes. 

## 
[CuPy Homepage](https://docs.cupy.dev/en/stable/index.html#)

[CuPy Github](https://github.com/cupy/cupy)

SyntaxError: invalid syntax (2804433560.py, line 3)